const hotels = [
  {
    id: "1",
    name: "Rovie Estate",
    location: "Buea, Cameroon",
    rating: 6.3,
    ratingStars: "⭐⭐⭐⭐⭐",
    price: 20000,
    currency: "XAF",
    reviews: "(64 reviews)",
    image: "https://via.placeholder.com/300x200.png?text=Hotel+1",
    latitude: 4.1584875,
    longitude: 9.2765634,
  },
  {
    id: "2",
    name: "Macsons Hotels",
    location: "Limbe - Karata Junction",
    rating: 9.6,
    ratingStars: "⭐⭐⭐⭐⭐",
    price: 55000,
    currency: "XAF",
    reviews: "(54 reviews)",
    image: "https://via.placeholder.com/300x200.png?text=Hotel+2",
    latitude: 4.0204749,
    longitude: 9.1792212,
  },
  {
    id: "3",
    name: "Label Elite Stay",
    location: "Buea - 13 Km from Tiko Golf Club",
    rating: 7.3,
    ratingStars: "⭐⭐⭐⭐⭐",
    price: 20000,
    currency: "XAF",
    reviews: "(13 reviews)",
    image: "https://via.placeholder.com/300x200.png?text=Hotel+3",
    latitude: 4.1450,
    longitude: 9.2550,
  },
  {
    id: "4",
    name: "Akhard Haus",
    location: "Buea - Molyko, UB South Street",
    rating: 8.1,
    ratingStars: "⭐⭐⭐⭐⭐",
    price: 15000,
    currency: "XAF",
    reviews: "(43 reviews)",
    image: "https://via.placeholder.com/300x200.png?text=Hotel+3",
    latitude: 4.1512333,
    longitude: 9.2886596,
  },
  {
    id: "5",
    name: "Armielia Apart Hotel",
    location: "Buea - Bokwai Road",
    rating: 8.2,
    ratingStars: "⭐⭐⭐⭐⭐",
    price: 25000,
    currency: "XAF",
    reviews: "(25 reviews)",
    image: "https://via.placeholder.com/300x200.png?text=Armielia+Hotel",
    latitude: 4.1675136,
    longitude: 9.2654928,
  },
  {
    id: "6",
    name: "WDC Apart Hotel",
    location: "Buea - Mile 16 Bolifamba",
    rating: 8.2,
    ratingStars: "⭐⭐⭐⭐⭐",
    price: 35000,
    currency: "XAF",
    reviews: "(24 reviews)",
    image: "https://via.placeholder.com/300x200.png?text=WDC+Hotel",
    latitude: 4.1472372,
    longitude: 9.3027837,
  },
];

export default hotels;