const hotels = [
  {
    id: "1",
    name: "Rovie Estate",
    location: "Buea, Cameroon",
    rating: 6.3,
    ratingStars: "⭐⭐⭐⭐⭐",
    price: 20000,
    currency: "XAF",
    reviews: "(64 reviews)",
    image: "https://via.placeholder.com/300x200.png?text=Hotel+1",
  },
  {
    id: "2",
    name: "Macsons Hotel",
    location: "Buea - Mile 16 Bolifamba",
    rating: 9.6,
    ratingStars: "⭐⭐⭐⭐⭐",
    price: 55000,
    currency: "XAF",
    reviews: "(54 reviews)",
    image: "https://via.placeholder.com/300x200.png?text=Hotel+2",
  },
  {
    id: "3",
    name: "Label Elite Stay",
    location: "Buea - 13 Km from Tiko Golf Club",
    rating: 7.3,
    ratingStars: "⭐⭐⭐⭐⭐",
    price: 20000,
    currency: "XAF",
    reviews: "(13 reviews)",
    image: "https://via.placeholder.com/300x200.png?text=Hotel+3",
  },
  {
    id: "4",
    name: "Akhard Haus",
    location: "Buea - Mile 16 Bolifamba",
    rating: 8.1,
    ratingStars: "⭐⭐⭐⭐⭐",
    price: 15000,
    currency: "XAF",
    reviews: "(43 reviews)",
    image: "https://via.placeholder.com/300x200.png?text=Hotel+3",
  },
  {
    id: "5",
    name: "Armielia Apart Hotel",
    location: "Buea - 17 Km from Tiko Golf Club",
    rating: 8.2,
    ratingStars: "⭐⭐⭐⭐⭐",
    price: 25000,
    currency: "XAF",
    reviews: "(25 reviews)",
    image: "https://via.placeholder.com/300x200.png?text=Armielia+Hotel",
  },
  {
    id: "6",
    name: "WDC Apart Hotel",
    location: "Buea - 17 Km from Tiko Golf Club", 
    rating: 8.2,
    ratingStars: "⭐⭐⭐⭐⭐",
    price: 35000,
    currency: "XAF",
    reviews: "(24 reviews)",
    image: "https://via.placeholder.com/300x200.png?text=WDC+Hotel",
  }
];

export default hotels;
