import { StyleSheet } from "react-native";
export const informationContainerStyles = StyleSheet.create({
  informationContainer: {
    backgroundColor: "white",
    height: 320,
    borderRadius: 10,
    marginBottom: 15,
    paddingHorizontal: 20,
    paddingVertical: 15,
    width: "100%",
  },
  title: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 5,
  },
  label: {
    fontSize: 14,
    fontWeight: "500",
    marginBottom: 5,
    color: "#333",
  },
  SearchButtonContents: {
    flexDirection: "row",
    gap: 12,
    alignItems: "center",
  },
  SearchButton: {
    backgroundColor: "white",
    height: 45,
    width: "100%",
    borderWidth: 1,
    borderColor: "lightgrey",
    borderRadius: 5,
    padding: 10,
    justifyContent: "center",
    marginVertical: 5,
  },
  DateButtonContents: {
    flexDirection: "row",
    gap: 10,
    alignItems: "center",
  },
  DateButton: {
    backgroundColor: "white",
    height: 45,
    width: "100%",
    borderWidth: 1,
    borderColor: "lightgrey",
    borderRadius: 5,
    justifyContent: "center",
    padding: 10,
    marginVertical: 5,
  },
  GuestInfoContainer: {
    borderWidth: 1,
    borderColor: "lightgrey",
    borderRadius: 5,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    height: 45,
    width: "100%",
    padding: 10,
    marginTop: 5,
    marginBottom: 10,
  },
});
